// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkivqgizlopjtuqcgqar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBraXZxZ2l6bG9wanR1cWNncWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzE4NDIsImV4cCI6MjA2MDgwNzg0Mn0.RWswny_0RyFtCo41_fLeyzKR-ejifHllJcdr1F9hO28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);